version: 2

defaults: &defaults
  docker:
    - image: circleci/clojure:lein-2.7.1
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx1g
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-clj-{{ checksum "project.clj" }}'
            - 'v1-clj-'
            - 'v1-test-'
      - run:
          name: Run tests
          command: lein test
      - save_cache:
          key: 'v1-clj-{{ checksum "project.clj" }}'
          paths:
            - ~/.m2
            - ~/.cljs/.aot_cache
      - persist_to_workspace:
          root: .
          paths: .
  test-cljs:
    working_directory: ~/test
    docker:
      - image: circleci/clojure:lein-2.8.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-cljs-{{ checksum "project.clj" }}-{{ checksum "package.json" }}'
            - 'v1-cljs-'
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run cljs tests
          command: lein do test-browser once, test-node once
      # - run:
      #     name: Run advanced tests
      #     command: lein test-advanced once
      - store_test_results:
          path: ~/test/target/results
      - save_cache:
          key: 'v1-cljs-{{ checksum "project.clj" }}-{{ checksum "package.json" }}'
          paths:
            - ~/.m2
            - ~/test/node_modules
  deploy:
    <<: *defaults
    requires:
      - build
    filters:
      branches:
        only: /master/
    steps:
      - attach_workspace:
          at: ~/repo
      - run: lein deploy clojars

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test-cljs:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test-cljs
          filters:
            branches:
              only: master
